use serde::Deserialize;

#[derive(Deserialize)]
struct SegRaw {
    v1: i16,
    v2: i16,
    angle: i16,
    linedef: i16,
    side: i16,
    offset: i16,
}



// LineSeg, generated by splitting LineDefs
// using partition lines selected by BSP builder.